Global:
  model: TimesNet_cls
  mode: check_dataset # check_dataset/train/evaluate/predict
  dataset_dir: "/home/software/gradio_apps/temp/press_machine/dataset/dataset/press_formatted"
  device: gpu:0
  output: "/home/software/gradio_apps/temp/press_machine/output"

CheckDataset:
  convert: 
    enable: False
    src_dataset_type: null
  split: 
    enable: False
    train_percent: null
    val_percent: null

Train:
  time_col: time
  target_cols: dim_0,dim_1,dim_2,dim_3,dim_4,dim_5,dim_6,dim_7,dim_8,dim_9,dim_10,dim_11
  group_id: group_id
  static_cov_cols: label
  freq: 1
  epochs_iters: 100
  batch_size: 16
  learning_rate: 0.0001
  log_interval: 10
  use_revin: True

Evaluate:
  weight_path: "/home/software/gradio_apps/temp/press_machine/output/best_model/model.pdparams"

Export:
  weight_path: https://paddle-model-ecology.bj.bcebos.com/paddlex/official_pretrained_model/TimesNet_cls.pdparams.tar

Predict:
  batch_size: 1
  model_dir: "/home/software/gradio_apps/temp/press_machine/output/inference"
  input: "https://paddle-model-ecology.bj.bcebos.com/paddlex/ts/demo_ts/ts_cls.csv"
