Global:
  model: PP-YOLOE_plus-S
  mode: check_dataset
  dataset_dir: "/home/software/gradio_apps/model/industrail_metric_det/dataset/meter_det"
  device: gpu:0,1
  output: "/home/software/gradio_apps/model/industrail_metric_det/output/det_model_output/det_model_output/det_model_output"

CheckDataset:
  convert:
    enable: False
    src_dataset_type: null
  split:
    enable: False
    train_percent: null
    val_percent: null

Train:
  num_classes: 1
  epochs_iters: 100
  batch_size: 8
  learning_rate: 0.001
  pretrain_weight_path: https://paddle-model-ecology.bj.bcebos.com/paddlex/official_pretrained_model/PP-YOLOE_plus-S_obj365_pretrained.pdparams 
  warmup_steps: 4000
  resume_path: null
  log_interval: 10
  eval_interval: 1
  lr_decay_epochs: [210, 240]
  lr_decay_gamma: 0.1
  transforms:
    train:
      - Decode: {}
      - RandomDistort: {}
      - RandomExpand: {}
      - RandomCrop: {}
      - Resize:
          target_size: 608
          interp: 'RANDOM'
      - RandomHorizontalFlip: {}
      - Normalize:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    eval:
      - Decode: {}
      - Resize:
          target_size: 608
          interp: 'CUBIC'
      - Normalize:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

Evaluate:
  weight_path: "/home/software/gradio_apps/model/industrail_metric_det/output/det_model_output/det_model_output/det_model_output/best_model/best_model.pdparams"
  log_interval: 10

Export:
  weight_path: https://paddle-model-ecology.bj.bcebos.com/paddlex/official_pretrained_model/PP-YOLOE_plus-S_pretrained.pdparams

Predict:
  batch_size: 1
  model_dir: "/home/software/gradio_apps/model/industrail_metric_det/model/PP-YOLOE_plus-S"
  input: "https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_object_detection_002.png"
  kernel_option:
    run_mode: paddle
