Global:
  model: PP-OCRv5_mobile_det
  mode: check_dataset # check_dataset/train/evaluate/predict
  module: text_det
  dataset_dir: "/home/software/gradio_apps/model/ele_metric_ocr/dataset/M2025"
  device: gpu:0,1
  output: "/home/software/gradio_apps/model/ele_metric_ocr/output"

CheckDataset:
  convert:
    enable: False
    src_dataset_type: null
  split:
    enable: False
    train_percent: null
    val_percent: null

Train:
  epochs_iters: 100
  batch_size: 4
  learning_rate: 0.001
  pretrain_weight_path: https://paddle-model-ecology.bj.bcebos.com/paddlex/official_pretrained_model/PP-OCRv5_mobile_det_pretrained.pdparams
  resume_path: null
  log_interval: 10
  eval_interval: 1
  save_interval: 1

Evaluate:
  weight_path: "/home/software/gradio_apps/model/ele_metric_ocr/output/best_accuracy/best_accuracy.pdparams"
  log_interval: 1

Export:
  weight_path: https://paddle-model-ecology.bj.bcebos.com/paddlex/official_pretrained_model/PP-OCRv5_mobile_det_pretrained.pdparams

Predict:
  batch_size: 1
  model_dir: "/home/software/gradio_apps/model/ele_metric_ocr/output/best_accuracy/inference"
  input: "https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_ocr_001.png"
  kernel_option:
    run_mode: paddle
