name: Build Latest Docker Image

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # 建议更新到 v4

    - name: Free up disk space on the runner
      run: |
        echo "Starting to free up space..."
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo docker image prune -af
        echo "Disk space after cleanup:"
        df -h

    - name: Login to Docker Hub
      uses: docker/login-action@v3 # 建议更新到 v3
      with:
        registry: ${{ secrets.DOCKER_HUB_REGISTER }}
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5 # 建议更新到 v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_REGISTER }}/ughost-docker/gradio_apps:latest
